Refactor of basicblock.py main loop and fuzzerstate
cascade-artifacts-designs/cascade-meta pull request #13
Opened 2024-10-18 07:25 UTC by bantierr

This patch attempts to improve the readability of the main loop of the basic block building loop by splitting generation steps more clearly and adding some getter and setter functions to some heavily used members of the fuzzerstate.

2024-10-18 16:32 UTC, flaviens requested changes

2024-10-18 16:32 UTC, flaviens commented on fuzzer/cascade/memview.py
>      # @param end:      last address of the range, excluded.
Please edit this comment like # @param sizeL size of the range, in bytes

2024-10-18 16:32 UTC, flaviens commented on fuzzer/cascade/memview.py
> +    def alloc_mem_range(self, start: int, alloc_range: int):
I'd prefer `alloc_size` (or `size`) as `range` has a specific meaning in Python already.

2024-10-18 16:32 UTC, flaviens commented on fuzzer/cascade/randomize/pickfpuop.py
> +    ret = None
I'd rather say ret = [], otherwise in the future the check on `len(ret)` might be problematic

2024-10-18 16:32 UTC, flaviens commented on fuzzer/cascade/fuzzerstate.py
> +    def add_instruction(self, new_instrobjs):
Please add some comments for the new functions to tell quickly their effect, and in which contexts they should or should not be used.

2024-10-18 16:32 UTC, flaviens commented
Hi @bantierr , thank you very much for your PR. This will be very helpful. Can you please try to fuzz a healthy CPU and a buggy CPU to see if both respond as you would expect? For that one easy option would be to pull the Cascade original docker, apply your changes and fuzz again the designs there.
I also added some minor comments in the review.
Thanks!

2024-10-19 13:31 UTC, bantierr commented
Hi Flavien, 
Thank you for the review. I applied all the chnages you suggested and fuzzed a healthy and buggy CPU with upstream and my chnages. 
I used the picorv32/picorv32-p5 and the kronos/kronos-k1 combinations. Both experiments had the expected behaviour, no timeouts on the healthy core, and fast timeouts on the buggy cores, on both upstream and my fork. 
I tried the reduce algorithm with both cascade versions as well, using the same timeout parameters. Both version found the same bug at the same location.
Please let me know if you think I should do some additional tests or if the descriptions are not fitting !
Have a nice day :) !

2024-10-20 00:34 UTC, flaviens approved these changes

2024-10-20 00:34 UTC, merged